In [20]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_excel(r"C:\Abinaya\NumpyNinja\phython hackathon\HospitalDatabase .xlsx",sheet_name=None)
edvisits=df['EDVisits']

In [14]:
edvisits

EDVisitID  PatientID               VisitDate         EDDischargeTime  \
0             1          1 2020-01-01 00:00:00.000 2020-01-01 11:20:22.924   
1            12         12 2020-01-01 02:45:40.302 2020-01-02 02:00:00.517   
2            13         13 2020-01-01 03:09:24.701 2020-01-01 05:00:20.852   
3            14         14 2020-01-01 03:12:19.349 2020-01-01 04:32:29.142   
4            15         15 2020-01-01 03:46:32.698 2020-01-01 06:24:52.741   
...         ...        ...                     ...                     ...   
1194       1183        929 2020-01-15 10:38:42.570 2020-01-16 02:31:52.023   
1195       1186        932 2020-01-15 11:52:37.540 2020-01-16 10:19:41.570   
1196       1187        933 2020-01-15 12:11:11.678 2020-01-15 16:41:15.223   
1197       1188        934 2020-01-15 12:21:46.006 2020-01-15 18:32:21.060   
1198       1189        935 2020-01-15 12:51:14.875 2020-01-15 23:40:41.456   

      Acuity ReasonForVisit EDDisposition           EDTime  
0          1   Stomach Ache      Admitted  11:20:22.924000  
1          2       Migraine      Admitted  02:00:00.517000  
2          3   Stomach Ache      Admitted  05:00:20.852000  
3          3       Migraine      Admitted  04:32:29.142000  
4          3     Chest Pain      Admitted  06:24:52.741000  
...      ...            ...           ...              ...  
1194       4     Chest Pain    Discharged  02:31:52.023000  
1195       1      Pneumonia    Discharged  10:19:41.570000  
1196       1      Pneumonia    Discharged  16:41:15.223000  
1197       1      Pneumonia    Discharged  18:32:21.060000  
1198       1      Pneumonia    Discharged  23:40:41.456000  

[1199 rows x 8 columns]

In [7]:
edvisits['EDTime']=pd.to_datetime(edvisits['EDDischargeTime']).dt.time

In [19]:

#edvisits.groupby('ReasonForVisit')['EDTime'].sum()

AttributeError: 'numpy.ndarray' object has no attribute 'groupby'

# Q 61 np.arange(1,31).reshape(6,5) Find the array slicing to get the elements with values 11,12,16,17.

In [25]:
array=np.arange(1,31).reshape(6,5)
print(array)
array[2:4,0:2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[11, 12],
       [16, 17]])

## Q 62 Create a dataframe with acuity and EDDisposition as the indices and the count of number of patients as the value.

In [37]:
Newdf=pd.DataFrame(edvisits.groupby(['Acuity','EDDisposition']).agg(Count_Of_Patients=('PatientID','count')))
Newdf


Count_Of_Patients
Acuity EDDisposition                   
1      Admitted                      32
       Discharged                   558
2      Admitted                     116
       Discharged                    66
3      Admitted                      81
4      Admitted                     107
       Discharged                    30
5      Admitted                     179
       Discharged                    30

# Q 63 List male patients over the age of 60 who have undergone surgery from January-March 2019.

In [38]:
patients=df['Patients']
patients

PatientID FirstName  LastName             DateOfBirth Gender  \
0            1     Lanni       Sue 1960-01-01 00:00:00.000   Male   
1            2       Far     Myers 1985-11-15 02:08:42.090   Male   
2            3   Devlin    Michael 1976-04-15 02:52:09.762   Male   
3            4   Carmine     Texas 1968-10-15 03:32:13.635   Male   
4            5     Tann       Bama 1962-05-01 19:12:58.950   Male   
..         ...       ...       ...                     ...    ...   
940        941       Wat   Fideler 1986-05-26 00:01:19.761   Male   
941        942    Wandie  Baythrop 1970-06-10 21:41:03.814   Male   
942        943   Diahann   Smeeton 1983-01-08 21:49:27.884   Male   
943        944  Panchito   Sharple 1963-06-05 07:57:05.569   Male   
944        945     Walsh    Calvie 1972-08-06 03:40:03.454   Male   

                       Race Language  
0                     White  English  
1                     White  English  
2                     White  English  
3                     White  English  
4                     White  English  
..                      ...      ...  
940  Black/African-American  English  
941  Black/African-American  English  
942  Black/African-American  English  
943  Black/African-American  English  
944  Black/African-American  English  

[945 rows x 7 columns]

In [51]:
from datetime import datetime
now = datetime.now()
patients['age']=(now-patients['DateOfBirth']).astype('<m8[Y]')

In [73]:
patients


VisitID  PatientMRN  ProviderID DateofVisit           DateScheduled  \
0        202         840          29  2019-03-19 2019-03-13 07:59:24.000   
1        436         820          25  2019-03-19 2019-02-24 07:10:31.043   
2        794         879          30  2019-04-02 2019-03-19 01:41:55.656   
3        799         884          37  2019-03-03 2019-02-25 01:25:39.696   
4        515          32          26  2019-03-16 2019-02-20 06:44:59.617   
..       ...         ...         ...         ...                     ...   
945      788         873           1  2019-03-27 2019-03-10 17:19:48.264   
946      703         855          36  2019-03-12 2019-02-19 02:27:52.664   
947      481         865          13  2019-05-03 2019-04-25 13:37:57.501   
948      398         635          10  2019-02-09 2019-02-08 11:40:35.137   
949      695         847          24  2019-03-04 2019-02-05 05:29:30.587   

     VisitDepartmentID     VisitType  BloodPressureSystolic  \
0                   10      Physical                  188.0   
1                    3     Follow Up                  179.0   
2                   11  Telemedicine                  133.0   
3                    4  Telemedicine                  132.0   
4                   11  Telemedicine                  131.0   
..                 ...           ...                    ...   
945                  5  Telemedicine                  187.0   
946                 10     Follow Up                  182.0   
947                 12           New                  150.0   
948                  1      Physical                  177.0   
949                 12     Follow Up                  165.0   

     BloodPressureDiastolic      Pulse VisitStatus  
0                144.143427  83.044920     No Show  
1                118.876808  90.309544     No Show  
2                 98.749563  80.859776     No Show  
3                 98.001270  82.184737     No Show  
4                 85.115632  89.192362     No Show  
..                      ...        ...         ...  
945              126.695141  70.049167    Canceled  
946              140.703502  73.380812    Canceled  
947               84.841197  61.625454    Canceled  
948              125.037534  53.287036    Canceled  
949              116.879318  56.180317    Canceled  

[950 rows x 11 columns]

In [78]:
ambulatoryvisits=df['AmbulatoryVisits']
providers=df['Providers']
ambulatoryvisits.rename(columns={'PatientMRN':'PatientID'},inplace=True)


In [79]:
pat_ambu=pd.merge(patients,ambulatoryvisits,how='inner',on='PatientID')

In [81]:

pat_ambu_provid=pd.merge(pat_ambu,providers,how='left',on='ProviderID')

In [82]:
pat_ambu_provid

PatientID  FirstName  LastName             DateOfBirth  Gender  \
0            4    Carmine     Texas 1968-10-15 03:32:13.635    Male   
1            5      Tann       Bama 1962-05-01 19:12:58.950    Male   
2            6  Jerrilyn       Kane 1969-03-30 09:36:56.550    Male   
3            7    Skipton       Bar 1975-11-25 22:23:53.525    Male   
4            8  Alexandra     Green 1967-06-16 16:37:21.694    Male   
..         ...        ...       ...                     ...     ...   
945        916     Kaylil   Baldack 1966-11-17 14:10:35.224  Female   
946        916     Kaylil   Baldack 1966-11-17 14:10:35.224  Female   
947        916     Kaylil   Baldack 1966-11-17 14:10:35.224  Female   
948        916     Kaylil   Baldack 1966-11-17 14:10:35.224  Female   
949        917     Velvet  Bushnell 1965-11-13 07:26:58.889  Female   

                       Race Language   age  VisitID  ProviderID  ...  \
0                     White  English  54.0        1           1  ...   
1                     White  English  60.0        2           2  ...   
2                     White  English  54.0        3           3  ...   
3                     White  English  47.0        4           4  ...   
4                     White  English  55.0        5           5  ...   
..                      ...      ...   ...      ...         ...  ...   
945  Black/African-American  English  56.0      831           4  ...   
946  Black/African-American  English  56.0      898          34  ...   
947  Black/African-American  English  56.0      278           2  ...   
948  Black/African-American  English  56.0      764          15  ...   
949  Black/African-American  English  57.0      279           3  ...   

              DateScheduled VisitDepartmentID  VisitType  \
0   2018-12-17 09:08:02.824                 1        New   
1   2018-12-20 12:52:48.286                 2        New   
2   2018-12-18 20:48:08.960                 3        New   
3   2018-12-21 19:47:47.631                 4        New   
4   2018-12-18 19:38:26.156                 5        New   
..                      ...               ...        ...   
945 2019-02-11 18:20:38.164                12  Follow Up   
946 2019-03-17 16:20:15.179                10        New   
947 2019-02-24 11:38:24.749                 2   Physical   
948 2019-02-15 12:31:44.307                 5  Follow Up   
949 2019-02-27 09:07:44.922                 3   Physical   

    BloodPressureSystolic  BloodPressureDiastolic      Pulse  VisitStatus  \
0                   175.0              139.096031  56.678398    Completed   
1                   158.0              116.151006  59.360770    Completed   
2                   154.0               98.736556  67.425256    Completed   
3                   137.0               85.844944  97.442262    Completed   
4                   167.0              130.334212  71.301478    Completed   
..                    ...                     ...        ...          ...   
945                 179.0              130.049131  76.114584    Completed   
946                 163.0               98.169357  67.506466    Completed   
947                 180.0              122.011558  76.224581    Completed   
948                 163.0              122.076264  99.794604    Completed   
949                 161.0              115.016508  67.455019    Completed   

        ProviderName ProviderSpecialty     ProviderDateOnStaff  
0          Sally Sue        Pediatrics 1993-01-01 00:00:00.000  
1         Mike Myers        Pediatrics 1993-05-02 00:00:17.695  
2     Jordan Michael        Pediatrics 1993-06-24 21:31:46.687  
3          Ted Texas        Pediatrics 1993-12-23 21:33:52.299  
4           Ala Bama        Pediatrics 1995-01-10 02:53:47.838  
..               ...               ...                     ...  
945        Ted Texas        Pediatrics 1993-12-23 21:33:52.299  
946       Tony Creed       PrimaryCare 2010-04-28 14:11:26.802  
947       Mike Myers        Pediatrics 1993-05-02 00:00: